# Generated by Django 4.2.7 on 2023-11-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45, unique=True)),
                ('date_created', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45, unique=True)),
                ('unit_price', models.IntegerField(default=0)),
                ('sales_price', models.IntegerField(default=0)),
                ('unit_measure', models.CharField(max_length=10)),
                ('date_updated', models.DateField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mabrokapp.equipmentcategory')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactions_id', models.AutoField(primary_key=True, serialize=False)),
                ('transactions_type', models.CharField(max_length=10)),
                ('stock_taken', models.IntegerField(default=0)),
                ('transactions_amount', models.IntegerField(default=0)),
                ('transactions_date', models.DateField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mabrokapp.products')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
